# ========= system global ========== #
models:
    mugen:
        model_name: MUGen
        agent_name: DeepSpeedAgent

seed: 13
max_length: 8192 # max length of the user input prompt
logging_step: 5
num_clip_tokens: 77
gen_emb_dim: 768
pretrained_ckpt_path: ./ckpt/pretrained_ckpt/

# ========= LLM ========== #
vicuna_version: 7b_v0 # [7b_v0, ]

# ========= multimodal encoder ========== #
imagebind_version: huge

# ========= text-to-audio alignment tuning ========== #
n_audio_tokens: 24
text_emb_to_audio_layers: [-1]
num_gen_audio_tokens: 24
text_fc_to_audio_mode: transformer  # [qformer, transformer]
generation_model: musicgen # [musicgen, audioldm2]
num_output_tokens: 1024 # [1024, 1]

# ========= image diffusion model ========== #
image_diffusion: runwayml/stable-diffusion-v1-5 # [runwayml/stable-diffusion-v1-5, stabilityai/stable-diffusion-2]

# ========= video diffusion model ========== #
video_diffusion: cerspense/zeroscope_v2_576w

# ========= audio diffusion model ========== #
audio_diffusion:  /hpctmp/e0589920/MusicGen # [cvssp/audioldm-l-full, cvssp/audioldm-s-full-v2]
